#!/bin/bash

while true; do
  read -rsn1 input
  if [ "$input" = "w" ]; then
    curl -X 'POST' \
      'http://127.0.0.1:8000/clients/0/move' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
          "speed": 100
        }'
  fi
  if [ "$input" = "s" ]; then
    curl -X 'POST' \
      'http://127.0.0.1:8000/clients/0/move' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d '{
          "speed": 0
        }'
  fi
  if [ "$input" = "a" ]; then
		curl -X 'POST' \
			'http://127.0.0.1:8000/clients/0/rotate' \
			-H 'accept: application/json' \
			-H 'Content-Type: application/json' \
			-d '{
					"angle": -45
				}'
  fi
  if [ "$input" = "d" ]; then
		curl -X 'POST' \
			'http://127.0.0.1:8000/clients/0/rotate' \
			-H 'accept: application/json' \
			-H 'Content-Type: application/json' \
			-d '{
					"angle": 45
				}'
  fi
  if [ "$input" = "r" ]; then
		curl -X 'POST' \
			'http://127.0.0.1:8000/clients/0/rotate' \
			-H 'accept: application/json' \
			-H 'Content-Type: application/json' \
			-d '{
					"angle": 360
				}'
  fi
  if [ "$input" = "b" ]; then
		curl -X 'POST' \
			'http://127.0.0.1:8000/clients/0/beep'
  fi
  echo
done
